#服务端口
server:
  port: 18080
spring:
  application:
    name: tanhua-app-server
  redis:  #redis配置
    port: 6379
    host: localhost
  cloud:  #nacos配置
    nacos:
      discovery:
        server-addr: localhost:8848
dubbo:    #dubbo配置
  registry:
    address: spring-cloud://localhost
  consumer:
    check: false
tanhua:
  sms:
    signName: 物流云商
    templateCode: SMS_106590012
    accessKey: LTAI4GKgob9vZ53k2SZdyAC7
    secret: LHLBvXmILRoyw0niRSBuXBZewQ30la
  oss:
    accessKey: LTAI5tHTqJf7xBtu72YvcPqc
    secret: H3ApUOyIh7y57tAVK4FyjRMAtpvQaz
    endpoint: oss-cn-hangzhou.aliyuncs.com
    bucketName: tanhua-jamison
    url: https://tanhua-jamison.oss-cn-hangzhou.aliyuncs.com/
  aip:
    appId: 32114926
    apiKey: Pns9SUFAt1HrWhyGGPKgjOPs
    secretKey: eD0jgzjPGrrmFGzY8dHEOHxCqxcWfGnn
